controllers:
    resource: ../src/Controller/
    type: attribute
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_historical_data:
    path: /historical/data
    controller: App\Controller\HistoricalDataController::index