controllers:
    resource: ../src/Controller/
    type: attribute
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_historical_data:
    path: /historical/data
    controller: App\Controller\HistoricalDataController::index

app_historical_data_download:
    path: /historical/data/download
    controller: App\Controller\HistoricalDataController::download

download_xml_four_weeks:
    path: download/xml
    controller: App\Controller\DownloadXmlController::downloadXml